merchex/merchex/urls.py
# ~/projects/django-web-app/merchex/merchex/urls.py

from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'), # nouveau path poour vue listée
    path('bands/<int:id>/', views.band_detail, name='band-detail'), # modèle url pour vue détaillé
    path('bands/add/', views.band_create, name='band-create'),
    path('bands/<int:id>/change/', views.band_update, name='band-update'),
    path('bands/<int:id>/delete/', views.band_delete, name='band-delete'),
    path('about-us/', views.about, name='about'),
    
    path('contact-us/', views.contact, name='contact'),
    
    path('listings/<int:id>/', views.listings_detail, name='listings-detail'),
    path('listings/', views.listings_list, name='listings-list'),
    path('listings/add/', views.listings_create, name='listings-create'),
    path('listings/<int:id>/change/', views.listings_update, name='listings-update'),
    path('listings/<int:id>/delete/', views.listings_delete, name='listings-delete'),
    path('email-sent', views.contact, name='email-sent')
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class Band(models.Model):
    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(max_length=50)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2021)])
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)
    
    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'
        COUPE_DECALE = 'CD'
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)

    def __str__(self): #au lieu d'afficher « Band object (id number)» affichons le nom du groupe
        return f'{self.name}'


class Song(models.Model):
    title = models.fields.CharField(max_length=100)

class Listing(models.Model):
    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=1000)
    sold = models.fields.BooleanField(default=True)
    year = models.fields.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(2021)], blank=True)
    
    class Type(models.TextChoices):
        RECORDS = 'RCD'
        CLOTHING = 'CLT'
        POSTERS = 'PTR'
        MISCELLANEOUS ='MLS'

    def __str__(self):
        return f'{self.description}'
    type = models.fields.CharField(choices=Type.choices, max_length=5)

    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)


merchex/listings/forms.py
from django import forms
from listings.models import Band, Listing
class ContactUsForm(forms.Form):
   name = forms.CharField(required=False)
   email = forms.EmailField()
   message = forms.CharField(max_length=1000)

class BandForm(forms.ModelForm):
   class Meta:
      model = Band
      #fields = '__all__'
      exclude = ('active', 'official_homepage')

class ListingForm(forms.ModelForm):
   class Meta:
      model = Listing
      fields = '__all__'


   

merchex/listings/views.py

# ~/projects/django-web-app/merchex/listings/views.py
from django.http import HttpResponse
from django.shortcuts import render
from listings.models import Band
from listings.models import Song
from listings.models import Listing
from listings.forms import ContactUsForm, BandForm, ListingForm
from django.core.mail import send_mail
from django.shortcuts import redirect


def band_list(request):
    bands = Band.objects.all()
    return render(request, 'listings/band_list.html', {'bands': bands})

def band_detail(request, id):
    band = Band.objects.get(id = id) #la ligne permet d'obtenir le Band avec l'ID
    #return render(request,'listings/band_detail.html', {'id': id})  #création de la vue détaillée, en ajoutant l'id au modèle
    return render(request,'listings/band_detail.html', {'band': band}) #mise à jour de la vue pour passer le groupe au gabarit

def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            # créer une nouvelle « Band » et la sauvegarder dans la db
            band = form.save()
            # redirige vers la page de détail du groupe que nous venons de créer
            # nous pouvons fournir les arguments du motif url comme arguments à la fonction de redirection
            return redirect('band-detail', band.id)

    else:
        form = BandForm()
    return render(request, 'listings/band_create.html',{'form': form})

def band_update(request, id):
    band = Band.objects.get(id=id)#on récupère le model qui a pour ID celui passé en paramètre
    if request.method == 'POST':
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            # mettre à jour le groupe existant dans la base de données
            form.save()
            # rediriger vers la page détaillée du groupe que nous venons de mettre à jour
            return redirect('band-detail', band.id)
    else:
        form = BandForm(instance=band)
    return render(request,'listings/band_update.html', {'form': form})

def band_delete(request, id):
    band = Band.objects.get(id=id)  ## on récupère l'objet et on le passe au modèle
    if request.method == 'POST':
        # supprimer le groupe de la base de données
        band.delete()
        # rediriger vers la liste des groupes
        return redirect('band-list')

    # pas besoin de « else » ici. Si c'est une demande GET, continuez simplement
    return render(request, 'listings/band_delete.html', {'band': band})



def about(request):
    return HttpResponse('<h1>À propos</h1> <p>Nous adorons merch !</p>')

'''def listings_list(request):
    songls = Song.objects.all()
    return render(request, 'listings/listings_list.html', {'songs': songs})'''

def listings_list(request):
    listings = Listing.objects.all()
    return render(request, 'listings/listings_list.html', {'listings': listings})

def listings_detail(request, id):
    listing = Listing.objects.get(id=id)#on récupère l'annonce à partir de son ID
    return render(request, 'listings/listings_detail.html', {'listing': listing})
def listings_create(request):
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            #créer un nouveau annonce et enregistrer dans la base de données
            listings = form.save()
            #rediriger vers la page de détails des annonces qui vient d’être créée
            return redirect ('listings-detail', listings.id)
    else :
        form = ListingForm()
        
    return render (request,'listings/listings_create.html', {'form':form})

def listings_update(request, id):
    listing = Listing.objects.get(id=id)
    if request.method == 'POST':
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()
            return redirect('listings-detail', listing.id)
    else:
        form = ListingForm(instance=listing)
    return render(request, 'listings/band_update.html', {'form': form})
    
def listings_delete(request, id):
    listing = Listing.objects.get(id=id)
    if request.method == 'POST':
        listing.delete()
        return redirect('listings-list')
    return render(request, 'listings/listings_delete.html', {'listing':listing})


def contact(request):
    # ajoutez ces instructions d'impression afin que nous puissions jeter un coup d'oeil à « request.method » et à « request.POST »
    if request.method == 'POST':
        # créer une instance de notre formulaire et le remplir avec les données POST
        form = ContactUsForm(request.POST)
        if form.is_valid():
            send_mail(
            subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us form',
            message=form.cleaned_data['message'],
            from_email=form.cleaned_data['email'],
            recipient_list=['admin@merchex.xyz'],
        )
        
        return redirect('email-sent') # instruction de retour après une requete POST pour éviter un double POST
    

    # si le formulaire n'est pas valide, nous laissons l'exécution continuer jusqu'au return
    # ci-dessous et afficher à nouveau le formulaire (avec des erreurs).

    else:
    # ceci doit être une requête GET, donc créer un formulaire vide
        form = ContactUsForm()
    return render(request, 'listings/contact.html', {'form': form}) #passe ce formulaire au gabarit

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>A propos</h1>
<p>Nous sommes une agence qui met en contact artistes et évènements</p>
<p>Créer en Aout 2023 l'objectif est de créer ce site en full django</p>


{% endblock %}

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}
<h1> Créer un nouveau groupe </h1>

<form action="" method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
  </form>

{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Supprimer le groupe</h1>

<p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>

<form action="" method="post">
{% csrf_token %}
<input type="submit" value="Supprimer">
</form>

{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}
<h2>{{ band.name }}</h2>


 <li>Genre : {{ band.get_genre_display }}</li>
 <li>Année de formation : {{ band.year_formed }}</li>
 <li>Actif : {{ band.active | yesno }}</li>
 <li> <a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>

<p>{{ band.biography }}</p>

<!--- {% for listing in band.listing_set.all %}
<a href="{% url 'listings-list' %}"> Annonces du groupes </a>
{% endfor%} -->


<a href="{% url 'band-list' %}">Retour à tous les groupes</a>


{% endblock %} 

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Groupes</h1>
    
<ul>
    {% for band in bands %}
        <li>
            <a href="{% url 'band-detail' band.id %}">{{ band.name }}</a>
            -<a href="{% url 'band-update' band.id %}">[modifier]</a>
        </li> 
    {% endfor %}
</ul>

<p>J'ai {{ bands|length }} groupes préférés.</p>

<p><a href="{% url 'band-create' %}"> Créer un nouveau groupe </a></p>


{% endblock %}

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}
<h1> Mise à jour du groupe </h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
 </form>

{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}
<html>
    <head>
        <title>Merchex</title>
        <link rel="stylesheet" href="{% static 'listings/style.css' %}">
    </head>
    <body>
        
        <nav>
            <ul>
                <li><a href="{% url 'band-list' %}">Groupes</a></li>
                <li><a href="{% url 'listings-list' %}">Annonces</a></li>
                <li><a href="{% url 'contact' %}">Contact</a></li>
                <li><a href="{% url 'about' %}">A propos</a></li>
            </ul>
            
        </nav>

        {% block content %}{% endblock %}

    </body>
</html>

merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Contact!</h1>

<p>Nous sommes là pour vous aider.</p>

<form action="" method="post" novalidate>
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Envoyer">
</form>

<ul>
    <li><a href="">Facebook</a></li>
    <li><a href="">Whatsapp</a></li>
    <li><a href="">Instagram</a></li>
</ul>

{% endblock %}

merchex/listings/templates/listings/email-sent.html
{% extends 'listings/base.html' %}

{% block content %}

<h3> Email envoyé</h3>
<a href="{% url 'contact' %}">Retourner au formulaire</a>
<a href="{% url 'band-list' %}">Retour à tous les groupes</a>

{% endblock %}

merchex/listings/templates/listings/listings_create.html
{% extends 'listings/base.html' %}

{% block content %}
<h1> Créer une nouvelle annonce </h1>

<form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
  </form>

{% endblock %}

merchex/listings/templates/listings/listings_delete.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Supprimer l'annonce</h1>

<p>Etes-vous sûr de vouloir supprimer l'annonce : {{ listing.description }} ?</p>

<form action="" method="post">
{% csrf_token %}
<input type="submit" value="Supprimer">
</form>

{% endblock %}

merchex/listings/templates/listings/listings_detail.html
{% extends 'listings/base.html' %}

{% block content %}
<h2>{{ listing.description }}</h2>

<li>Sold: {{ listing.active | yesno }}</li>
<li>Année: {{ listing.year }}</li>
<li>Type d'article: {{ listing.get_type_display }}</li>
<li>Groupe: </li>

{% endblock %}

merchex/listings/templates/listings/listings_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Annonces!</h1>
     
<ul>            
    {% for listing in listings %}
        <li>
            <a href="{% url 'listings-detail' listing.id %}">{{ listing.description }}</a>
            -<a href="{% url 'listings-update' listing.id %}">[modifier]</a>

        </li>
    {% endfor %}
</ul>

<a href="{% url 'listings-create' %}"> Créer une nouvelle annonce</a>

{% endblock %}

merchex/listings/templates/listings/listings_update.html
{% extends 'listings/base.html' %}

{% block content %}
<h1> Mise à jour de l'annonce </h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">
 </form>